#!/usr/bin/env bash
#
# install-kk.sh - Installer for kk (Kubernetes Power Helper CLI)
#
# Run as root or via:  sudo bash install-kk.sh
#

set -euo pipefail

OS_NAME="$(uname -s 2>/dev/null || echo unknown)"
IS_DARWIN=0
if [[ "$OS_NAME" == "Darwin" ]]; then
  IS_DARWIN=1
fi

KK_URL_DEFAULT="https://raw.githubusercontent.com/heart/kk-Kubernetes-Power-Helper-CLI/main/kk.sh"
INSTALL_PATH_DEFAULT="/usr/local/lib/kk.sh"
PROFILE_SNIPPET_DEFAULT="/etc/profile.d/kk.sh"

KK_URL="${KK_URL:-$KK_URL_DEFAULT}"
INSTALL_PATH="${INSTALL_PATH:-$INSTALL_PATH_DEFAULT}"
PROFILE_SNIPPET="${PROFILE_SNIPPET:-$PROFILE_SNIPPET_DEFAULT}"

if [[ -z "${SKIP_PROFILE_SNIPPET+x}" ]]; then
  SKIP_PROFILE_SNIPPET="0"
  SKIP_PROFILE_SNIPPET_SET_BY_USER=0
else
  SKIP_PROFILE_SNIPPET_SET_BY_USER=1
fi

SKIP_PROFILE_SNIPPET_AUTO_REASON=""
if [[ "$SKIP_PROFILE_SNIPPET_SET_BY_USER" -eq 0 && "$IS_DARWIN" -eq 1 ]]; then
  SKIP_PROFILE_SNIPPET="1"
  SKIP_PROFILE_SNIPPET_AUTO_REASON="(macOS detected, /etc/profile.d not auto-loaded)"
fi

echo "[kk-installer] Using source URL:    $KK_URL"
echo "[kk-installer] Target install path: $INSTALL_PATH"
if [[ "$SKIP_PROFILE_SNIPPET" == "1" ]]; then
  if [[ -n "$SKIP_PROFILE_SNIPPET_AUTO_REASON" ]]; then
    echo "[kk-installer] Profile snippet:     (skipped) $SKIP_PROFILE_SNIPPET_AUTO_REASON"
  else
    echo "[kk-installer] Profile snippet:     (skipped)"
  fi
else
  echo "[kk-installer] Profile snippet:     $PROFILE_SNIPPET"
fi

if [[ "$EUID" -ne 0 ]]; then
  echo "[kk-installer] ERROR: Please run this script as root, e.g.:"
  echo "  sudo bash install-kk.sh"
  exit 1
fi

TMP_FILE="$(mktemp /tmp/kk.XXXXXX)"

cleanup() {
  rm -f "$TMP_FILE"
}
trap cleanup EXIT

LOCAL_SOURCE=""
if [[ "$KK_URL" == file://* ]]; then
  LOCAL_SOURCE="${KK_URL#file://}"
elif [[ -f "$KK_URL" ]]; then
  LOCAL_SOURCE="$KK_URL"
fi

if [[ -n "$LOCAL_SOURCE" ]]; then
  echo "[kk-installer] Using local kk source: $LOCAL_SOURCE"
  cp "$LOCAL_SOURCE" "$TMP_FILE"
else
  echo "[kk-installer] Downloading kk ..."
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$KK_URL" -o "$TMP_FILE"
  elif command -v wget >/dev/null 2>&1; then
    wget -q "$KK_URL" -O "$TMP_FILE"
  else
    echo "[kk-installer] ERROR: curl or wget is required to download kk."
    exit 1
  fi
fi

if [[ ! -s "$TMP_FILE" ]]; then
  echo "[kk-installer] ERROR: Downloaded file is empty. Aborting."
  exit 1
fi

if [[ -e "$INSTALL_PATH" || -L "$INSTALL_PATH" ]]; then
  BACKUP_PATH="${INSTALL_PATH}.bak.$(date +%Y%m%d%H%M%S)"
  echo "[kk-installer] Existing kk found at $INSTALL_PATH"
  echo "[kk-installer] Backing up to $BACKUP_PATH"
  mv "$INSTALL_PATH" "$BACKUP_PATH"
fi

INSTALL_DIR="$(dirname "$INSTALL_PATH")"
mkdir -p "$INSTALL_DIR"

echo "[kk-installer] Installing kk to $INSTALL_PATH ..."
mv "$TMP_FILE" "$INSTALL_PATH"

chown root:root "$INSTALL_PATH"
chmod 644 "$INSTALL_PATH"

if [[ "$SKIP_PROFILE_SNIPPET" != "1" ]]; then
  PROFILE_DIR="$(dirname "$PROFILE_SNIPPET")"
  mkdir -p "$PROFILE_DIR"
  {
    echo "# kk (Kubernetes Power Helper CLI) - auto-sourced function"
    echo "# Generated by install-kk.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo "if [ -f \"$INSTALL_PATH\" ]; then"
    echo "  # shellcheck source=/dev/null"
    echo "  . \"$INSTALL_PATH\""
    echo "fi"
  } > "$PROFILE_SNIPPET"
  chmod 644 "$PROFILE_SNIPPET"
  echo "[kk-installer] Created profile snippet at $PROFILE_SNIPPET"
  echo "[kk-installer] Open a new shell (or source the snippet) to load kk()."
else
  echo "[kk-installer] SKIP_PROFILE_SNIPPET=1 -> not writing profile snippet."
  echo "[kk-installer] Remember to source $INSTALL_PATH from your shell rc file."
fi

echo "[kk-installer] Done."
echo "[kk-installer] kk function is installed at: $INSTALL_PATH"
echo "[kk-installer] Try:  kk ns show  or  kk pods (after opening a new shell)"

if [[ "$IS_DARWIN" -eq 1 ]]; then
  cat <<EOF
[kk-installer] NOTE: macOS does not automatically source /etc/profile.d files.
[kk-installer] Add the following line to your shell startup file (e.g. ~/.zshrc or ~/.bash_profile):
[kk-installer]   source "$INSTALL_PATH"
EOF
fi
